// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2KexePPqOjFi3x_88tRTKrANTuJka0ok',
    appId: '1:863948634021:web:bdbff46180a14f49f91a4c',
    messagingSenderId: '863948634021',
    projectId: 'flutter-stock-e2b0e',
    authDomain: 'flutter-stock-e2b0e.firebaseapp.com',
    storageBucket: 'flutter-stock-e2b0e.firebasestorage.app',
    measurementId: 'G-D6SX3KYLQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPGYnGRgI533Iwj38NjjIKPTail6Qdo6o',
    appId: '1:863948634021:android:45f6356f8e3d717ef91a4c',
    messagingSenderId: '863948634021',
    projectId: 'flutter-stock-e2b0e',
    storageBucket: 'flutter-stock-e2b0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ7SMX_sbh3VrwOU9BfnFQ9TMIw09qD8M',
    appId: '1:863948634021:ios:b3260d7d3641faaaf91a4c',
    messagingSenderId: '863948634021',
    projectId: 'flutter-stock-e2b0e',
    storageBucket: 'flutter-stock-e2b0e.firebasestorage.app',
    iosBundleId: 'com.haruka.stockApp',
  );

}