-- Create companies table (Master Data)
CREATE TABLE IF NOT EXISTS companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    stock_code TEXT,
    official_url TEXT,
    logo_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_companies_stock_code ON companies(stock_code);

-- Enable Row Level Security
ALTER TABLE companies ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Companies: Public read access
CREATE POLICY "Allow public read access on companies" ON companies
    FOR SELECT USING (true);
