-- Create stores table (Map Data)
CREATE TABLE IF NOT EXISTS stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES companies(id),
    name TEXT NOT NULL,
    store_brand TEXT,
    address TEXT,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    geog GEOGRAPHY(POINT, 4326),
    category_tag TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_stores_company_id ON stores(company_id);
CREATE INDEX IF NOT EXISTS idx_stores_geog ON stores USING GIST(geog);

-- Enable Row Level Security
ALTER TABLE stores ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Stores: Public read access
CREATE POLICY "Allow public read access on stores" ON stores
    FOR SELECT USING (true);
