-- Create users_yuutai table (User Holdings)
CREATE TABLE IF NOT EXISTS users_yuutai (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    company_id BIGINT REFERENCES companies(id),
    company_name TEXT,
    benefit_detail TEXT,
    expiry_date DATE,
    status TEXT DEFAULT 'active', -- active, used, expired
    alert_enabled BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    notes TEXT,
    notify_days_before INTEGER[] DEFAULT '{}'
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_users_yuutai_user_id ON users_yuutai(user_id);

-- Enable Row Level Security
ALTER TABLE users_yuutai ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Users Yuutai: Users can manage their own data
CREATE POLICY "Users can view their own yuutai" ON users_yuutai
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own yuutai" ON users_yuutai
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own yuutai" ON users_yuutai
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own yuutai" ON users_yuutai
    FOR DELETE USING (auth.uid() = user_id);
